### ISSUE TITLE
EHCache TODO

### ISSUE THREAD

**Issue by ao508** [cBioPortal/clinical-data-dictionary#89]
TODO:
- [ ]  implement reading from ehcache when topbraid cannot be reached
- [ ] unit tests for implementation of ehcache results
- [ ] use maven filtering to inject new properties in `src/main/resources/application.properties` (i.e., persistence disk location, cache byte units, cache byte size, etc.)
- [ ] remove hardcoding of properties and location of `ehcache.xml`
- [ ] package `ehcache.xml` into war so that tomcat knows where to find it (did not work with simply using `classpath:ehcache.xml` in instantiation of `CacheManager` bean).
